version: '3'
services:
  heuristic-eval-db:
    image: mariadb
    container_name: heuristic-eval-db
    command: mysqld --character-set-server=utf8
    environment:
      - MYSQL_DATABASE=heuristic_evaluation
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./sql-files:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  heuristic-eval:
    build:
      context: .
    image: heuristic-eval
    container_name: heuristic-eval
    depends_on:
      - heuristic-eval-db
    ports:
      - "8080:80"
    environment:
      - MYSQL_DATABASE=heuristic_evaluation
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=heuristic-eval-db
      - MYSQL_PORT=3306
